image: alpine:latest
stages:
  - report
  - info
  - trigger
  - deploy

trigger_mobile:
  stage: trigger
  trigger:
    include: Frontend/Mobile/.gitlab-ci.yml
  rules:
      - changes:
          - Frontend/Mobile/**/*
      - when: manual

trigger_web:
  stage: trigger
  trigger:
    include: Frontend/Web/Dedale/.gitlab-ci.yml
    strategy: depend
  rules:
      - changes:
        - Frontend/Web/**/*
      - when: manual

pages:
  stage: report
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - report-www/*
        - report-www/**/*
  script:
    - rm -rf $CI_PROJECT_DIR/public
    - mkdir -p $CI_PROJECT_DIR/public
    - cp -r $CI_PROJECT_DIR/report-www/. $CI_PROJECT_DIR/public/
  artifacts:
    paths:
      - public