image: alpine:latest
stages:
  - info
  - trigger

print_mr_link:
  stage: info
  image: alpine:latest
  script:
    - |
      echo ""
      echo "🧠 Merge Request détectée"
      echo "-------------------------------------------"
      echo "💡 MR : ${CI_PROJECT_URL}/-/merge_requests/${CI_MERGE_REQUEST_IID}"
      echo "-------------------------------------------"
      echo ""
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

trigger_mobile:
  stage: trigger
  trigger:
    include: Frontend/Mobile/.gitlab-ci.yml
  rules:
      - changes:
          - Frontend/Mobile/**/*
      - when: manual

trigger_web:
  stage: trigger
  trigger:
    include: Frontend/Web/Dedale/.gitlab-ci.yml
    strategy: depend
  rules:
      - changes:
        - Frontend/Web/**/*
      - when: manual