stages:
  - info
  - trigger

print_mr_link:
  stage: info
  image: alpine:latest
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == feature/* ]]; then
        echo ""
        echo "🧠 Tu viens de pousser sur la branche : $CI_COMMIT_BRANCH"
        echo "-------------------------------------------"
        echo "💡 Crée ta Merge Request ici :"
        echo "👉 ${CI_PROJECT_URL}/-/merge_requests/new?merge_request[source_branch]=${CI_COMMIT_BRANCH}"
        echo "-------------------------------------------"
        echo ""
      fi
  only:
    - /^feature\/.*$/

trigger_mobile:
  stage: trigger
  trigger:
    include: Frontend/Mobile/.gitlab-ci.yml
  rules:
      - changes:
          - Frontend/Mobile/**/*
      - when: manual

trigger_web:
  stage: trigger
  trigger:
    include: Frontend/Web/Dedale/.gitlab-ci.yml
    strategy: depend
  rules:
      - changes:
        - Frontend/Web/**/*
      - when: manual