services:
  # Profil "web"
  tile-server:
    build: ./Backend
    profiles: ["web"]
    ports:
      - "8082:8080"
    volumes:
      - ./Backend/tiles:/data

  nominatim:
    image: mediagis/nominatim:5.2
    profiles: ["web"]
    environment:
      PBF_URL: https://download.geofabrik.de/europe/france/alsace-latest.osm.pbf
      NOMINATIM_CORS: '*'
    ports:
      - "8081:8080"
    volumes:
      - nominatim-data:/var/lib/postgresql/16/main

  # Profil "mobile"
  mobile-tile-server:
    image: node:22
    profiles: ["mobile"]
    working_dir: /app
    command: >
      bash -c "npm install && 
      node ./tile-server.js"
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/Mobile/Dedale:/app
      - /app/node_modules
    develop:
      watch:
        - path: ./Frontend/Mobile/Dedale
          action: sync
          target: /app
          ignore:
            - node_modules/
        - path: ./Frontend/Mobile/Dedale/package.json
          action: rebuild
   
volumes:
  nominatim-data:
