# Dockerfile pour React Router v7 SSR
FROM node:20-alpine
WORKDIR /app

# Copier package.json et installer les dépendances
COPY /api/package*.json ./
RUN npm install

# Copier le code source
COPY ./api .

# Builder l'application React Router SSR
RUN npm run build

# Exposer le port où ton serveur va tourner
EXPOSE 8000

# Lancer le serveur Node
CMD ["npm", "start"]