# Tester le site sur un serveur local : mkdocs serve
# Build du site : mkdocs build

site_name: Rapport T6

site_dir: public

extra_css:
  - css/custom.css

nav:
  - Rapport 1: index.md
  - FAQ: FAQ.md
