// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/accueil": {
    params: {};
  };
  "/carte": {
    params: {};
  };
  "/equipes": {
    params: {};
  };
  "/planning": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/accueil" | "/carte" | "/equipes" | "/planning";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/";
  };
  "routes/accueil.tsx": {
    id: "routes/accueil";
    page: "/accueil";
  };
  "routes/carte.tsx": {
    id: "routes/carte";
    page: "/carte";
  };
  "routes/equipes.tsx": {
    id: "routes/equipes";
    page: "/equipes";
  };
  "routes/planning.tsx": {
    id: "routes/planning";
    page: "/planning";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/accueil": typeof import("./app/routes/accueil.tsx");
  "routes/carte": typeof import("./app/routes/carte.tsx");
  "routes/equipes": typeof import("./app/routes/equipes.tsx");
  "routes/planning": typeof import("./app/routes/planning.tsx");
};