stages: 
  - quality

image: node:22-slim

lint:
  stage: quality
  before_script:
    - cd Frontend/Mobile/Dedale
    - npm install -g eas-cli
    - npm install
  script:
    - npx expo lint > mobile_lint.txt || true
  artifacts:
    paths: 
      - Frontend/Mobile/Dedale/mobile_lint.txt
    expire_in: 1 week
    when: always
  allow_failure: true
